In [53]:
import pandas as pd
import glob

# 폴더 경로 설정
folder_path = "./goods/"

# 폴더 내의 모든 CSV 파일 경로를 가져오기
csv_files = glob.glob(folder_path + "*.csv")

# 각 CSV 파일을 데이터프레임으로 읽고 리스트에 저장
df_list = [pd.read_csv(file) for file in csv_files]

# 개별 데이터프레임 변수로 저장 (예시: df_samu_data1, df_samu_data2, ...)
for idx, df in enumerate(df_list, 1):
    globals()[f'df_samu_data{idx}'] = df

In [54]:
len(df_list)

28

In [55]:
# df_list의 모든 데이터프레임을 결합하여 하나의 데이터프레임으로 생성
combined_df = pd.concat(df_list, ignore_index=True)

# 결합된 데이터프레임의 정보 출력
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4484 entries, 0 to 4483
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   goodsKey         0 non-null      float64
 1   category1        4484 non-null   object
 2   category2        4484 non-null   object
 3   category3        4484 non-null   object
 4   ASIN             4484 non-null   object
 5   goodsName        4484 non-null   object
 6   brand            4213 non-null   object
 7   originalPrice    4484 non-null   int64
 8   discountedPrice  4484 non-null   int64
 9   ratingAvg        4124 non-null   float64
 10  ratingCount      4124 non-null   float64
 11  goodsInfo        4452 non-null   object
 12  goodsDesc        2514 non-null   object
dtypes: float64(3), int64(2), object(8)
memory usage: 455.5+ KB

In [56]:
#추천 output 해당하는 데이터 가져올 총합 데이터프레임 (프론트 출력시)
#combined_df.info()

In [57]:
#추천 modeling 용 데이터프레임
df = combined_df
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4484 entries, 0 to 4483
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   goodsKey         0 non-null      float64
 1   category1        4484 non-null   object
 2   category2        4484 non-null   object
 3   category3        4484 non-null   object
 4   ASIN             4484 non-null   object
 5   goodsName        4484 non-null   object
 6   brand            4213 non-null   object
 7   originalPrice    4484 non-null   int64
 8   discountedPrice  4484 non-null   int64
 9   ratingAvg        4124 non-null   float64
 10  ratingCount      4124 non-null   float64
 11  goodsInfo        4452 non-null   object
 12  goodsDesc        2514 non-null   object
dtypes: float64(3), int64(2), object(8)
memory usage: 455.5+ KB

In [58]:
df.columns

Index(['goodsKey', 'category1', 'category2', 'category3', 'ASIN', 'goodsName',
       'brand', 'originalPrice', 'discountedPrice', 'ratingAvg', 'ratingCount',
       'goodsInfo', 'goodsDesc'],
      dtype='object')

In [59]:
#분류가 맨앞으로 나오게 열 순서 변경
order = ['category1', 'category2', 'category3', 'goodsKey', 'ASIN', 'goodsName',
       'brand', 'originalPrice', 'discountedPrice', 'ratingAvg', 'ratingCount',
       'goodsInfo', 'goodsDesc']
df = df[order]
df

,category1,category2,category3,goodsKey,ASIN,goodsName,brand,originalPrice,discountedPrice,ratingAvg,ratingCount,goodsInfo,goodsDesc
0,사무용품,라벨 및 스티커,다목적 라벨,NaN,B000GOWKOE,"MACO 화이트 사각형 다목적 라벨, 3/8 x 5/8 인치, 박스 당 1000 (...",Maco,8185,8185,4.3,30.0,"3/8 x 5/8 인치 라벨, 박스 당 1000 라벨 다양한 용도로 완벽한 라벨. ...",MACO White Rectangular Multi-Purpose Labels ar...
1,사무용품,라벨 및 스티커,다목적 라벨,NaN,B0083FX8EE,"Avery 다용도 라벨, 제거 가능, 다양한 네온, 2.625인치, 360팩 (6479)",AVERY,27104,18960,4.6,157.0,밝은 네온 색상으로 필요한 것을 빠르게 찾을 수 있습니다 라벨은 붙어서 그대로 유지...,필요한 것을 순식간에 찾을 수 있도록 도와주는 탈착식 네온 라벨로 색상 코딩과 구성...
2,사무용품,라벨 및 스티커,다목적 라벨,NaN,B07CQFBHD9,DYMO Authentic LabelWriter LabelWriter 라벨 프린터용...,DYMO,83086,83086,4.7,1312.0,500개의 라벨 6롤 포함(각 2.5cm x 5.7cm(1인치 x 2 1/8인치))...,DY LW 2.5cm X 5.4cm 화이트 멀티 500CT 6팩
3,사무용품,라벨 및 스티커,다목적 라벨,NaN,B008OTCWWI,"Avery 다용도 라벨, 탈착식, 다양한 네온, 5.1 x 10.2cm(2 x 4인...",AVERY,26190,17644,4.6,227.0,밝은 네온 색상으로 필요한 것을 순식간에 찾을 수 있습니다 라벨은 붙어 있고 그대로...,이제 필요한 것을 순식간에 찾을 수 있도록 도와주는 탈착식 네온 라벨로 색상 코딩과...
4,사무용품,라벨 및 스티커,다목적 라벨,NaN,B0CKLGSJKF,"정품 P21 라벨 메이커 테이프, 적응 라벨 인쇄 용지, 14x40mm(0.55x1...",Nelko,22146,22146,4.7,173.0,【P21 라벨 메이커 테이프】이 열 라벨 테이프는 Nelko P21 프린터에 특별히...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4479,식음료,음료,커피,NaN,B09Z6C8N3V,"Roast Ridge 그라운드 콜드 브루 커피 블렌드, 0.9kg(2파운드)",Roast Ridge,22035,22035,4.4,262.0,능선에서 번성하세요! Roast Ridge Coffees는 높은 고도에서 생산되는 ...,능선에서 번성하세요! Roast Ridge Coffees는 높은 고도에서 생산되는 ...
4480,식음료,음료,커피,NaN,B07KXH7V7P,"Bulletproof Breakfast Blend 라이트 로스트 원두 커피, 355...",Bulletproof,22146,22146,4.4,488.0,"라이트 로스트 원두 커피: 밀크 초콜릿, 오렌지, 베리, 시트러스의 생생한 노트 고...",NaN
4481,식음료,음료,커피,NaN,B08XZR4ZTQ,"Martinson 클래식 다크 로스트 커피, 큐리그 K-Cup 브루어 호환 포드, ...",Martinson,52630,52630,4.4,567.0,"정통 맛: 당사의 클래식 다크 로스트는 균형 잡히고 매끄러우며, 견과류 향과 약간의...",Martinson 커피는 100년 이상 Joe Martinson 자신이 설립한 것과...
4482,식음료,음료,커피,NaN,B09XGB219K,"Death Wish Coffee Co., Organic and Fair Trade ...",Death Wish Coffee,24209,24209,4.6,777.0,카페인의 추가 킥: Death Wish Coffee 에스프레소 로스트는 풍부한 커피...,NaN
4483,식음료,음료,커피,NaN,B0BFVQ6NLK,"VitaCup 하이드레이션 커피 포드, 전해질로 수분을 공급하는 최초의 커피, 코코...",VitaCup,41480,41480,4.1,195.0,커피의 신화; 반박! 커피가 수분을 공급하나요? 이제 걱정 없이 마실 수 있습니다....,NaN

In [60]:
df.to_csv("추.csv", index =False)

In [61]:
data = pd.read_csv('추.csv')
keywords = pd.read_csv('grouped_keywords.csv')
keywords

             ASIN                                           KeyWords
0      9935970434  ['페이지', '섹션', '작업', '레이아웃', '신축', '디자인', '프로젝트...
1      B00004YTJF  ['보이지', '테이프', '디스펜서', '영구', '롤', '마감', '매트', ...
2      B00004Z65P  ['라벨', '스티커', '선물', '교실', '탈착', '식별', '프린터', '...
3      B00005C3YY  ['테이프', '보이지', '스펜서', '마법', '선호', '안전하다', '영구'...
4      B00005C8R6  ['접착제', '스틱', '크레욜', '학생', '건조하다', '글루', '넓다',...
...           ...                                                ...
4673   B0DDZDQNKW  ['버섯', '장제', '강', '프리', '포커스', '초콜릿', '체리', '일...
4674   B0DDZNLJP7  ['캔디', '초콜릿', '버터', '땅콩', '달콤하다', '간식', '파티', ...
4675   B0DDZP495Q  ['초콜릿', '버터', '민트', '땅콩', '유청', '상자', '단백질', '...
4676   B0DFD3N5MB  ['풀', '프리', '단백질', '설탕', '글루텐', '케이크', '초콜릿', ...
4677  ‎B098NC3W5H  ['볼펜', '잉크', '리필', '블랙', '스타일러스', '처리', '메탈', ...

[4678 rows x 2 columns]

In [62]:
joined_df = data.merge(keywords, on='ASIN', how='inner')
joined_df.info()
joined_df.to_csv("df_for_model.csv", index =False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4484 entries, 0 to 4483
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   category1        4484 non-null   object
 1   category2        4484 non-null   object
 2   category3        4484 non-null   object
 3   goodsKey         0 non-null      float64
 4   ASIN             4484 non-null   object
 5   goodsName        4484 non-null   object
 6   brand            4213 non-null   object
 7   originalPrice    4484 non-null   int64
 8   discountedPrice  4484 non-null   int64
 9   ratingAvg        4124 non-null   float64
 10  ratingCount      4124 non-null   float64
 11  goodsInfo        4452 non-null   object
 12  goodsDesc        2514 non-null   object
 13  KeyWords         4484 non-null   object
dtypes: float64(3), int64(2), object(9)
memory usage: 490.6+ KB

### 여기부터 피클 차용..

In [63]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

data = pd.read_csv('df_for_model.csv')

# keyword 리스트를 문자열로 변환
data['keyword_str'] = data['KeyWords'].apply(lambda x: ' '.join(eval(x)))

# TF-IDF 벡터화
tfidf = TfidfVectorizer()
tfidf_matrix = tfidf.fit_transform(data['keyword_str'])

In [35]:
# 유사 제품 추천 함수 정의 (가격 필터링x)
def recommend_products_keyword(index, num_recommendations=5):
    # 주어진 제품과 다른 제품들 간의 코사인 유사도 계산
    cosine_sim = cosine_similarity(tfidf_matrix[index], tfidf_matrix).flatten()
    
    # 입력한 제품의 인덱스를 제외하고 유사한 제품의 인덱스 추출
    similar_indices = cosine_sim.argsort()[::-1]  # 유사도 높은 순으로 정렬
    similar_indices = similar_indices[similar_indices != index]  # 자기 자신 제외
    
    # 가장 유사한 제품 5개 추출
    top_similar_indices = similar_indices[:num_recommendations]
    
    # 유사도 값과 함께 추천 제품 반환 (유사도 높은 순서대로)
    recommendations = data.iloc[top_similar_indices][['category1', 'category2', 'category3', 'goodsName', 'KeyWords']].copy()
    recommendations['similarity'] = cosine_sim[top_similar_indices]  # 유사도 값 추가
    return recommendations

In [38]:
# 사용자 입력을 받아 제품 추천 (스크롤링 파트)
while True:
    try:
        # 사용자에게 인덱스 입력 받기
        user_input = int(input(f"추천받을 제품의 인덱스 번호를 입력하세요 (0 ~ {len(data)-1}): "))
        
        # 입력 값이 데이터 범위 내에 있는지 확인
        if 0 <= user_input < len(data):
            # 추천 시스템 실행 및 결과 출력
            recommendations = recommend_products_keyword(user_input, num_recommendations=5)
            print("\n유사한 제품 추천 결과:")
            print(recommendations[['category1', 'category2', 'category3', 'goodsName', 'KeyWords', 'similarity']])
            break  # 올바른 입력이 있으면 루프 종료
        else:
            print(f"유효하지 않은 인덱스입니다. 0에서 {len(data)-1} 사이의 값을 입력하세요.")
            
    except ValueError:
        print("올바른 숫자를 입력하세요.")

추천받을 제품의 인덱스 번호를 입력하세요 (0 ~ 4483):  7

유사한 제품 추천 결과:
   category1 category2 category3  \
84      사무용품  라벨 및 스티커    다목적 라벨
30      사무용품  라벨 및 스티커    다목적 라벨
14      사무용품  라벨 및 스티커    다목적 라벨
1       사무용품  라벨 및 스티커    다목적 라벨
52      사무용품  라벨 및 스티커    다목적 라벨

                                            goodsName  \
84      Avery 탈착식 8.9 x 10.2 cm 화이트 ID 라벨 150팩 (6464)
30  Avery 자가 접착 제거 가능한 라벨, 0.625 x 0.87 인치, 화이트, 팩...
14       Avery 탈착식 다용도 라벨, 다양한 네온, 8.9 x 10.2cm(3 1/3
1   Avery 다용도 라벨, 제거 가능, 다양한 네온, 2.625인치, 360팩 (6479)
52  Avery 인쇄 가능한 다목적 탈착식 라벨, 5.1 x 10.2cm(2 x 4인치)...

                                             KeyWords  similarity
84  ['라벨', '인쇄', '프린터', '탈착', '제거', '유지', '붙이', '흰...    0.591106
30  ['라벨', '제거', '서랍', '깨끗하다', '유지', '용기', '선반', '...    0.401918
14                   ['라벨', '제거', '네온', '탈착', '깨끗하다']    0.364418
1              ['라벨', '네온', '제거', '깨끗하다', '탈착', '요구']    0.327061
52               ['라벨', '탈착', '인쇄', '정리', '포장', '맞춤']    0.309968

In [39]:
# 사용자 입력을 받아 제품 추천 #추천멘트부분
while True:
    try:
        # 사용자에게 인덱스 입력 받기
        user_input = int(input(f"추천받을 제품의 인덱스 번호를 입력하세요 (0 ~ {len(data)-1}): "))
        
        # 입력 값이 데이터 범위 내에 있는지 확인
        if 0 <= user_input < len(data):
            # 사용자가 조회한 제품명 가져오기
            selected_product_name = data.iloc[user_input]['goodsName']
            
            # 추천 시스템 실행
            recommendations = recommend_products_keyword(user_input, num_recommendations=5)
            
            # 사용자 메시지 출력
            print(f"\n최근 '{selected_product_name}' 상품을 알아보셨군요, 이 상품들은 어떠신가요?\n")
            
            # 추천 결과 출력
            print(recommendations[['category1', 'category2', 'category3', 'goodsName', 'KeyWords', 'similarity']])
            break  # 올바른 입력이 있으면 루프 종료
        else:
            print(f"유효하지 않은 인덱스입니다. 0에서 {len(data)-1} 사이의 값을 입력하세요.")
            
    except ValueError:
        print("올바른 숫자를 입력하세요.")

추천받을 제품의 인덱스 번호를 입력하세요 (0 ~ 4483):  77

최근 'BETCKEY Dymo 30332 (2.5 x 2.5cm(1 x 1인치)) 정사각형 QR 코드의 다목적 라벨과 호환되는 컬러 라벨, Dymo LabelWriter 450, 4XL 및 Zebra 데스크탑 프린터와 호환 [2롤 1500 라벨. Light, els, 블루]' 상품을 알아보셨군요, 이 상품들은 어떠신가요?

    category1 category2 category3  \
11       사무용품  라벨 및 스티커    다목적 라벨
121      사무용품  라벨 및 스티커    다목적 라벨
92       사무용품  라벨 및 스티커    다목적 라벨
70       사무용품  라벨 및 스티커    다목적 라벨
49       사무용품  라벨 및 스티커    다목적 라벨

                                             goodsName  \
11   DYMO 30334 호환 가능 5.7 x 3.2cm(2-1/4 x 1-1/4인치) ...
121  HOUSELABELS DYMO 30336 호환 다용도 라벨(2.5cm x 5.4cm...
92   Phomemo M110/M120/M200/M220/M221 라벨 메이커 프린터와 호...
70   Phomemo M110/M120/M200/M220/M221 라벨 메이커 프린터와 호...
49   5.1cm(2인치) 핑크 원형 열 라벨, 컬러 열 라벨, MUNBYN, Nelko,...

                                              KeyWords  similarity
11        ['라벨', '호환', '프린터', '바코드', '다목적', '다용', '롤']    0.675232
121                     ['라벨', '호환', '프린터', '롤', '방지']    0.612195
92   ['라벨', '인쇄', '블랙', '투명', '접착', '열', '다목적', '프린...    0.602100
70   ['라벨', '인쇄', '블랙', '화이트', '접착', '바탕', '열', '다목...    0.570758
49           ['라벨', '스티커', '열', '프린터', '식', '롤', '호환']    0.564581

In [50]:
# 유사 제품 추천 함수 정의 (가격 필터링o)
def recommend_products_discounted_price(index, num_recommendations=5):
    # 주어진 제품과 다른 제품들 간의 코사인 유사도 계산
    cosine_sim = cosine_similarity(tfidf_matrix[index], tfidf_matrix).flatten()
    
    # 입력한 제품의 인덱스를 제외하고 유사한 제품의 인덱스 추출
    similar_indices = cosine_sim.argsort()[::-1]  # 유사도 높은 순으로 정렬
    similar_indices = similar_indices[similar_indices != index]  # 자기 자신 제외
    
    # 선택한 제품의 할인된 가격
    selected_product_price = data.iloc[index]['discountedPrice']

    # 유사도가 높은 제품 중에서 할인된 가격이 선택한 제품의 가격보다 낮거나 같은 제품만 필터링
    filtered_indices = [i for i in similar_indices if data.iloc[i]['discountedPrice'] <= selected_product_price]

    # 필터링된 인덱스를 기반으로 유사도가 높은 순서로 상위 N개의 제품 추출
    top_filtered_indices = filtered_indices[:num_recommendations]

    # 유사도 값과 함께 추천 제품 반환 (유사도 높은 순서대로)
    recommendations = data.iloc[top_filtered_indices][['category1', 'category2', 'category3', 'goodsName', 'KeyWords', 'originalPrice',
       'discountedPrice']].copy()
    recommendations['similarity'] = cosine_sim[top_filtered_indices]  # 유사도 값 추가
    return recommendations

In [64]:
#가격이 봤던 상품보다 낮은 것으로 필터링해서 추천
while True:
    try:
        # 사용자에게 인덱스 입력 받기
        user_input = int(input(f"추천받을 제품의 인덱스 번호를 입력하세요 (0 ~ {len(data)-1}): "))
        
        # 입력 값이 데이터 범위 내에 있는지 확인
        if 0 <= user_input < len(data):
            # 사용자가 조회한 제품명 가져오기
            selected_product_name = data.iloc[user_input]['goodsName']
            # 사용자가 조회한 제품의 discounted_price 가져오기
            selected_product_discounted_price = data.iloc[user_input]['discountedPrice']
        
            # 추천 시스템 실행
            recommendations = recommend_products_discounted_price(user_input, num_recommendations=5)
            
            # 사용자 메시지 출력
            print(f"\n최근 '{selected_product_name}' 상품을 알아보셨군요, '{selected_product_discounted_price}'원 보다 더 낮은 가격의 상품이 있습니다.\n")
            
            # 추천 결과 출력
            print(recommendations[['category1', 'category2', 'category3', 'goodsName', 'KeyWords', 'originalPrice',
       'discountedPrice', 'similarity']])
            break  # 올바른 입력이 있으면 루프 종료
        else:
            print(f"유효하지 않은 인덱스입니다. 0에서 {len(data)-1} 사이의 값을 입력하세요.")
            
    except ValueError:
        print("올바른 숫자를 입력하세요.")

추천받을 제품의 인덱스 번호를 입력하세요 (0 ~ 4483):  898

최근 '21.6 x 27.9cm(8-1/2 x 11인치) 다목적 변조 방지 무단 복사 방지 그린 보안 용지, (100개 팩)' 상품을 알아보셨군요, '23531'원 보다 더 낮은 가격의 상품이 있습니다.

     category1 category2    category3  \
639       사무용품  마커 및 형광펜          형광펜
1739      사무용품       테이프       투명 테이프
867       사무용품        종이  복사 및 다목적 용지
572       사무용품  마커 및 형광펜          형광펜
541       사무용품  마커 및 형광펜          형광펜

                                              goodsName  \
639                 STABILO BOSS 오리지널 하이라이터, 미디엄 핑크쉬 레드
1739  Scotch 8102P3472 매직 테이프 리필, 1.9cm(3/4인치) x 659...
867   Amazon Basics 30% 재활용 다용도 복사 프린터 용지 - 21.6 x 2...
572   feela 12가지 색상 성경 젤 하이라이터, 젤 하이라이터 마커 스터디 키트, 하...
541   feela 젤 형광펜 24팩, 12가지 다양한 색상 성경 형광펜 마커 저널링 용품,...

                                               KeyWords  originalPrice  \
639   ['하이라이터', '디자인', '잉크', '캡', '사본', '방지', '미디엄',...           6925
1739  ['테이프', '보이지', '사본', '펜', '롤', '종이', '영구', '연필...          29085
867   ['용지', '프린터', '복사', '재활용', '화이트', '복사기', '종이',...          13282
572   ['하이라이터', '휴대', '무독성', '성경', '서비스', '사무실', '빠르...          11066
541   ['형광', '펜', '보안', '시스루', '성능', '성경', '서비스', '사...          19390

      discountedPrice  similarity
639              6925    0.199941
1739            21398    0.181813
867             13282    0.157809
572             11066    0.156180
541             16606    0.154017